//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class All
    {
        public int Id { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<int> HouseNumber { get; set; }
        public Nullable<int> FlatNummber { get; set; }
        public Nullable<int> Latitude { get; set; }
        public Nullable<int> Longitude { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<int> NumberOfRooms { get; set; }
        public Nullable<int> NumberOfFloors { get; set; }
        public Nullable<int> Area { get; set; }
        public string TypeObject { get; set; }
    }
}
